export const occasionsData = [
  // Día a día
  { slug: 'universidad', name: 'Universidad', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'dia-casual', name: 'Día casual', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'hacer-mandados', name: 'Hacer mandados', group: 'Día a día', formalityMin: 1, formalityMax: 2 },
  { slug: 'ir-de-compras', name: 'Ir de compras', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'cafe', name: 'Café', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'brunch', name: 'Brunch', group: 'Día a día', formalityMin: 2, formalityMax: 4 },
  { slug: 'comida-casual', name: 'Comida casual', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'reunion-familiar', name: 'Reunión familiar', group: 'Día a día', formalityMin: 2, formalityMax: 3 },
  { slug: 'viaje', name: 'Viaje', group: 'Día a día', formalityMin: 1, formalityMax: 2 },
  { slug: 'aeropuerto', name: 'Aeropuerto', group: 'Día a día', formalityMin: 1, formalityMax: 2 },
  { slug: 'dia-en-casa', name: 'Día en casa', group: 'Día a día', formalityMin: 1, formalityMax: 1 },
  { slug: 'dia-lluvioso', name: 'Día lluvioso', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'dia-caluroso', name: 'Día caluroso', group: 'Día a día', formalityMin: 1, formalityMax: 3 },
  { slug: 'dia-frio', name: 'Día frío', group: 'Día a día', formalityMin: 1, formalityMax: 3 },

  // Trabajo y actividades profesionales
  { slug: 'oficina', name: 'Oficina', group: 'Trabajo y actividades profesionales', formalityMin: 3, formalityMax: 5 },
  { slug: 'trabajo-creativo', name: 'Trabajo creativo', group: 'Trabajo y actividades profesionales', formalityMin: 2, formalityMax: 4 },
  { slug: 'reunion-trabajo', name: 'Reunión de trabajo', group: 'Trabajo y actividades profesionales', formalityMin: 4, formalityMax: 5 },
  { slug: 'presentacion', name: 'Presentación', group: 'Trabajo y actividades profesionales', formalityMin: 4, formalityMax: 5 },
  { slug: 'entrevista', name: 'Entrevista', group: 'Trabajo y actividades profesionales', formalityMin: 4, formalityMax: 5 },
  { slug: 'evento-profesional', name: 'Evento profesional', group: 'Trabajo y actividades profesionales', formalityMin: 3, formalityMax: 5 },
  { slug: 'cena-de-negocios', name: 'Cena de negocios', group: 'Trabajo y actividades profesionales', formalityMin: 4, formalityMax: 5 },

  // Social
  { slug: 'cita-de-dia', name: 'Cita de día', group: 'Social', formalityMin: 2, formalityMax: 4 },
  { slug: 'cita-romantica', name: 'Cita romántica', group: 'Social', formalityMin: 3, formalityMax: 5 },
  { slug: 'cena', name: 'Cena', group: 'Social', formalityMin: 2, formalityMax: 5 },
  { slug: 'cumpleanos', name: 'Cumpleaños', group: 'Social', formalityMin: 3, formalityMax: 5 },
  { slug: 'fiesta', name: 'Fiesta', group: 'Social', formalityMin: 3, formalityMax: 5 },
  { slug: 'reunion-amigas', name: 'Reunión con amigas', group: 'Social', formalityMin: 2, formalityMax: 4 },
  { slug: 'rooftop', name: 'Rooftop', group: 'Social', formalityMin: 3, formalityMax: 5 },
  { slug: 'concierto', name: 'Concierto', group: 'Social', formalityMin: 1, formalityMax: 3 },
  { slug: 'festival', name: 'Festival', group: 'Social', formalityMin: 1, formalityMax: 3 },
  { slug: 'antro-club', name: 'Antro o club', group: 'Social', formalityMin: 3, formalityMax: 5 },
  { slug: 'noche-casual', name: 'Noche casual', group: 'Social', formalityMin: 2, formalityMax: 4 },

  // Celebraciones
  { slug: 'boda-de-dia', name: 'Boda de día', group: 'Celebraciones', formalityMin: 4, formalityMax: 5 },
  { slug: 'boda-de-noche', name: 'Boda de noche', group: 'Celebraciones', formalityMin: 4, formalityMax: 5 },
  { slug: 'graduacion-propia', name: 'Graduación propia', group: 'Celebraciones', formalityMin: 5, formalityMax: 5 },
  { slug: 'invitada-graduacion', name: 'Invitada a graduación', group: 'Celebraciones', formalityMin: 4, formalityMax: 5 },
  { slug: 'bautizo-comunion', name: 'Bautizo o primera comunión', group: 'Celebraciones', formalityMin: 3, formalityMax: 4 },
  { slug: 'baby-shower', name: 'Baby shower', group: 'Celebraciones', formalityMin: 2, formalityMax: 4 },
  { slug: 'despedida', name: 'Despedida', group: 'Celebraciones', formalityMin: 3, formalityMax: 4 },
  { slug: 'coctel', name: 'Cóctel', group: 'Celebraciones', formalityMin: 4, formalityMax: 5 },
  { slug: 'cena-formal', name: 'Cena formal', group: 'Celebraciones', formalityMin: 4, formalityMax: 5 },
  { slug: 'gala', name: 'Gala', group: 'Celebraciones', formalityMin: 5, formalityMax: 5 },
  { slug: 'etiqueta', name: 'Etiqueta', group: 'Celebraciones', formalityMin: 5, formalityMax: 5 },

  // Viajes y descanso
  { slug: 'playa', name: 'Playa', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 2 },
  { slug: 'alberca', name: 'Alberca', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 2 },
  { slug: 'comida-playa', name: 'Comida en la playa', group: 'Viajes y descanso', formalityMin: 2, formalityMax: 3 },
  { slug: 'cena-playa', name: 'Cena en la playa', group: 'Viajes y descanso', formalityMin: 3, formalityMax: 4 },
  { slug: 'resort', name: 'Resort', group: 'Viajes y descanso', formalityMin: 3, formalityMax: 4 },
  { slug: 'paseo-turistico', name: 'Paseo turístico', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 2 },
  { slug: 'road-trip', name: 'Road trip', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 2 },
  { slug: 'dia-deportivo', name: 'Día deportivo', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 2 },
  { slug: 'cozy', name: 'Cozy', group: 'Viajes y descanso', formalityMin: 1, formalityMax: 1 }
];

export const outfitData = [
  {
    slug: 'campus-marfil',
    name: 'Campus Marfil',
    description: 'Outfit casual pulido, perfecto para universidad o café.',
    formalityScore: 2,
    comfortScore: 4,
    occasionTags: ['universidad', 'cafe', 'dia-casual'],
    styleTags: ['casual pulido'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['blanco', 'azul denim', 'beige', 'dorado'],
    imagePrompt: 'Fotografía editorial flat lay de un outfit femenino completo...'
  },
  {
    slug: 'universidad-relajada',
    name: 'Universidad Relajada',
    description: 'Estética universitaria elegante y cómoda.',
    formalityScore: 2,
    comfortScore: 5,
    occasionTags: ['universidad', 'biblioteca', 'hacer-mandados'],
    styleTags: ['casual cómodo'],
    weatherTags: ['templado'],
    colorPalette: ['azul cielo', 'crema', 'blanco', 'cafe']
  },
  {
    slug: 'cafe-con-encanto',
    name: 'Café con Encanto',
    description: 'Romántico casual para brunch o citas.',
    formalityScore: 3,
    comfortScore: 3,
    occasionTags: ['cafe', 'cita-de-dia', 'brunch'],
    styleTags: ['romántico casual'],
    weatherTags: ['templado'],
    colorPalette: ['marfil', 'champagne', 'nude', 'dorado']
  },
  {
    slug: 'brunch-dorado',
    name: 'Brunch Dorado',
    description: 'Vestido midi de lino luminoso y veraniego.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['brunch', 'comida-casual', 'cumpleanos'],
    styleTags: ['smart casual femenino'],
    weatherTags: ['caluroso', 'templado'],
    colorPalette: ['blanco cálido', 'arena', 'natural', 'dorado']
  },
  {
    slug: 'mandados-con-estilo',
    name: 'Mandados con Estilo',
    description: 'Casual funcional, práctico y sofisticado.',
    formalityScore: 2,
    comfortScore: 4,
    occasionTags: ['ir-de-compras', 'hacer-mandados', 'paseo-turistico'],
    styleTags: ['casual funcional'],
    weatherTags: ['templado', 'caluroso'],
    colorPalette: ['negro', 'crema', 'beige', 'dorado']
  },
  {
    slug: 'aeropuerto-elegante',
    name: 'Aeropuerto Elegante',
    description: 'Travel chic con máxima comodidad.',
    formalityScore: 2,
    comfortScore: 5,
    occasionTags: ['aeropuerto', 'viaje', 'road-trip'],
    styleTags: ['travel chic'],
    weatherTags: ['fresco', 'templado'],
    colorPalette: ['blanco', 'negro', 'gris topo', 'beige']
  },
  {
    slug: 'lluvia-refinada',
    name: 'Lluvia Refinada',
    description: 'Trench coat beige y pantalón técnico.',
    formalityScore: 2,
    comfortScore: 3,
    occasionTags: ['dia-lluvioso', 'universidad'],
    styleTags: ['casual urbano'],
    weatherTags: ['fresco', 'lluvia'],
    colorPalette: ['crema', 'beige', 'negro']
  },
  {
    slug: 'lino-verano',
    name: 'Lino de Verano',
    description: 'Conjunto de lino minimalista y fresco.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['dia-caluroso', 'comida-casual'],
    styleTags: ['minimalista de verano'],
    weatherTags: ['caluroso'],
    colorPalette: ['marfil', 'coñac', 'dorado']
  },
  {
    slug: 'capas-invierno',
    name: 'Capas de Invierno',
    description: 'Abrigo largo camel de lana con denim oscuro.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['dia-frio', 'cafe'],
    styleTags: ['clásico casual'],
    weatherTags: ['frio'],
    colorPalette: ['crema', 'azul oscuro', 'camel', 'cafe oscuro']
  },
  {
    slug: 'cozy-casa',
    name: 'Cozy en Casa',
    description: 'Suéter oversized avena y jogger.',
    formalityScore: 1,
    comfortScore: 5,
    occasionTags: ['dia-en-casa', 'cozy'],
    styleTags: ['cozy'],
    weatherTags: ['fresco', 'templado'],
    colorPalette: ['avena', 'crema', 'beige']
  },
  {
    slug: 'presentacion-impecable',
    name: 'Presentación Impecable',
    description: 'Blusa blanca de crepé y pantalón sastre azul marino.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['presentacion', 'evento-profesional'],
    styleTags: ['business casual'],
    weatherTags: ['templado'],
    colorPalette: ['blanco', 'azul marino', 'negro', 'dorado']
  },
  {
    slug: 'oficina-minimalista',
    name: 'Oficina Minimalista',
    description: 'Blazer camel y slingbacks nude.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['oficina', 'reunion-trabajo'],
    styleTags: ['business casual elegante'],
    weatherTags: ['templado'],
    colorPalette: ['marfil', 'beige', 'camel', 'nude']
  },
  {
    slug: 'reunion-ejecutiva',
    name: 'Reunión Ejecutiva',
    description: 'Vestido midi azul marino y blazer marfil.',
    formalityScore: 5,
    comfortScore: 2,
    occasionTags: ['reunion-trabajo', 'cena-de-negocios'],
    styleTags: ['formal profesional'],
    weatherTags: ['templado'],
    colorPalette: ['azul marino', 'marfil', 'nude', 'dorado']
  },
  {
    slug: 'entrevista-clasica',
    name: 'Entrevista Clásica',
    description: 'Sastre negro y camisa blanca.',
    formalityScore: 5,
    comfortScore: 3,
    occasionTags: ['entrevista', 'evento-profesional'],
    styleTags: ['formal profesional'],
    weatherTags: ['templado'],
    colorPalette: ['blanco', 'negro', 'dorado']
  },
  {
    slug: 'oficina-creativa',
    name: 'Oficina Creativa',
    description: 'Blusa verde olivo y pantalón crema.',
    formalityScore: 4,
    comfortScore: 4,
    occasionTags: ['trabajo-creativo', 'evento-profesional'],
    styleTags: ['moderno profesional'],
    weatherTags: ['templado'],
    colorPalette: ['verde olivo', 'crema', 'beige', 'cafe']
  },
  {
    slug: 'cena-casual',
    name: 'Cena Casual',
    description: 'Body negro, jeans oscuros y blazer beige.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['cena', 'cita-de-dia'],
    styleTags: ['smart casual'],
    weatherTags: ['fresco', 'templado'],
    colorPalette: ['negro', 'azul oscuro', 'beige', 'dorado']
  },
  {
    slug: 'cena-romantica',
    name: 'Cena Romántica',
    description: 'Vestido midi color vino.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['cita-romantica', 'cena'],
    styleTags: ['romántico elegante'],
    weatherTags: ['templado'],
    colorPalette: ['vino', 'negro', 'dorado']
  },
  {
    slug: 'cumpleanos-champagne',
    name: 'Cumpleaños Champagne',
    description: 'Top satinado champagne y pantalón negro.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['cumpleanos', 'fiesta'],
    styleTags: ['glam semiformal'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['champagne', 'negro', 'dorado']
  },
  {
    slug: 'noche-amigas',
    name: 'Noche con Amigas',
    description: 'Corset estructurado negro y jeans.',
    formalityScore: 3,
    comfortScore: 3,
    occasionTags: ['reunion-amigas', 'noche-casual'],
    styleTags: ['trendy'],
    weatherTags: ['fresco', 'templado'],
    colorPalette: ['negro', 'azul oscuro', 'vino', 'dorado']
  },
  {
    slug: 'rooftop-marfil',
    name: 'Rooftop Marfil',
    description: 'Top asimétrico marfil y sastre negro.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['rooftop', 'coctel'],
    styleTags: ['elegante moderno'],
    weatherTags: ['templado', 'caluroso'],
    colorPalette: ['marfil', 'negro', 'dorado']
  },
  {
    slug: 'concierto-urbano',
    name: 'Concierto Urbano',
    description: 'Falda piel vegana y chamarra de mezclilla.',
    formalityScore: 2,
    comfortScore: 3,
    occasionTags: ['concierto', 'noche-casual'],
    styleTags: ['urbano elegante'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['negro', 'mezclilla']
  },
  {
    slug: 'noche-glam',
    name: 'Noche Glam',
    description: 'Vestido corto negro con drapeado lateral.',
    formalityScore: 4,
    comfortScore: 2,
    occasionTags: ['fiesta', 'antro-club'],
    styleTags: ['glam'],
    weatherTags: ['templado'],
    colorPalette: ['negro', 'dorado']
  },
  {
    slug: 'coctel-negro-oro',
    name: 'Cóctel Negro y Oro',
    description: 'Vestido midi negro con accesorios dorados.',
    formalityScore: 4,
    comfortScore: 2,
    occasionTags: ['coctel', 'cena-formal'],
    styleTags: ['cóctel'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['negro', 'dorado']
  },
  {
    slug: 'boda-dia',
    name: 'Boda de Día',
    description: 'Vestido verde salvia.',
    formalityScore: 5,
    comfortScore: 3,
    occasionTags: ['boda-de-dia'],
    styleTags: ['formal de día'],
    weatherTags: ['caluroso', 'templado'],
    colorPalette: ['verde salvia', 'nude', 'beige']
  },
  {
    slug: 'boda-noche',
    name: 'Boda de Noche',
    description: 'Vestido largo azul profundo satinado.',
    formalityScore: 5,
    comfortScore: 2,
    occasionTags: ['boda-de-noche'],
    styleTags: ['formal'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['azul profundo', 'plateado', 'nude']
  },
  {
    slug: 'invitada-graduacion',
    name: 'Invitada a Graduación',
    description: 'Vestido midi rosa empolvado.',
    formalityScore: 4,
    comfortScore: 3,
    occasionTags: ['invitada-graduacion'],
    styleTags: ['semiformal'],
    weatherTags: ['templado'],
    colorPalette: ['rosa empolvado', 'nude', 'champagne', 'dorado']
  },
  {
    slug: 'mi-graduacion',
    name: 'Mi Graduación',
    description: 'Vestido midi blanco marfil.',
    formalityScore: 5,
    comfortScore: 3,
    occasionTags: ['graduacion-propia'],
    styleTags: ['formal personal'],
    weatherTags: ['templado'],
    colorPalette: ['blanco marfil', 'nude', 'beige']
  },
  {
    slug: 'celebracion-familiar',
    name: 'Celebración Familiar',
    description: 'Vestido midi azul cielo fluido.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['bautizo-comunion', 'baby-shower'],
    styleTags: ['semiformal de día'],
    weatherTags: ['templado', 'caluroso'],
    colorPalette: ['azul cielo', 'nude', 'crema', 'marfil']
  },
  {
    slug: 'gala-esmeralda',
    name: 'Gala Esmeralda',
    description: 'Vestido largo verde esmeralda mate.',
    formalityScore: 5,
    comfortScore: 2,
    occasionTags: ['gala', 'etiqueta'],
    styleTags: ['etiqueta'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['verde esmeralda', 'dorado', 'negro']
  },
  {
    slug: 'cena-formal-borgona',
    name: 'Cena Formal Borgoña',
    description: 'Vestido midi borgoña de terciopelo o crepé.',
    formalityScore: 5,
    comfortScore: 3,
    occasionTags: ['cena-formal'],
    styleTags: ['formal'],
    weatherTags: ['fresco', 'frio'],
    colorPalette: ['borgoña', 'negro', 'dorado']
  },
  {
    slug: 'dia-playa',
    name: 'Día de Playa',
    description: 'Traje de baño negro con lino oversized.',
    formalityScore: 1,
    comfortScore: 5,
    occasionTags: ['playa', 'alberca'],
    styleTags: ['resort casual'],
    weatherTags: ['caluroso'],
    colorPalette: ['negro', 'blanco', 'beige']
  },
  {
    slug: 'cena-playa',
    name: 'Cena en la Playa',
    description: 'Vestido largo terracota fluido.',
    formalityScore: 4,
    comfortScore: 4,
    occasionTags: ['cena-playa', 'resort'],
    styleTags: ['resort elegante'],
    weatherTags: ['caluroso', 'templado'],
    colorPalette: ['terracota', 'dorado', 'beige']
  },
  {
    slug: 'brunch-resort',
    name: 'Brunch de Resort',
    description: 'Falda estampada y halter blanco.',
    formalityScore: 3,
    comfortScore: 4,
    occasionTags: ['resort', 'comida-playa'],
    styleTags: ['resort chic'],
    weatherTags: ['caluroso'],
    colorPalette: ['blanco', 'azul', 'crema', 'beige']
  },
  {
    slug: 'paseo-ciudad',
    name: 'Paseo por la Ciudad',
    description: 'Rayas marineras y denim jacket.',
    formalityScore: 2,
    comfortScore: 5,
    occasionTags: ['paseo-turistico', 'road-trip'],
    styleTags: ['casual urbano'],
    weatherTags: ['templado', 'fresco'],
    colorPalette: ['marfil', 'negro', 'beige', 'mezclilla', 'camel']
  },
  {
    slug: 'festival-boho',
    name: 'Festival Boho Refinado',
    description: 'Short denim, top bordado y kimono ligero.',
    formalityScore: 2,
    comfortScore: 4,
    occasionTags: ['festival', 'concierto'],
    styleTags: ['boho moderno'],
    weatherTags: ['caluroso'],
    colorPalette: ['blanco', 'mezclilla', 'beige', 'cafe']
  },
  {
    slug: 'athleisure-pulido',
    name: 'Athleisure Pulido',
    description: 'Leggings negros y chamarra beige.',
    formalityScore: 1,
    comfortScore: 5,
    occasionTags: ['dia-deportivo', 'hacer-mandados'],
    styleTags: ['athleisure'],
    weatherTags: ['templado'],
    colorPalette: ['negro', 'beige', 'blanco']
  }
];
